apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: okd-trigger-example-pipeline
spec:
  params:
    - name: git-revision
      type: string
      description: The git repository revision to check out
      default: main
    - name: git-repo-url
      type: string
      description: The git repository to check out
    - name: git-repo-name
      type: string
      description: The git repository name
    - name: git-hash
      type: string
      description: The git repository commit hash
    - name: git-actor-name
      type: string
      description: The git repository revision authors name

  workspaces:
      - name: shared-workspace
    
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-repo-url)
        - name: revision
          value: $(params.git-revision)
        - name: subdirectory
          value: $(params.git-repo-name)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: src
          workspace: shared-workspace
    - name: merged-workflow
      params:
        - name: git-repo-name
          value: $(params.git-repo-name)
        - name: git-repo-url
          value: $(params.git-repo-url)
        - name: git-hash
          value: $(params.git-hash)
        - name: git-actor-name
          value: $(params.git-repo-name)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: okd-trigger-example-test
      workspaces:
        - name: src
          workspace: shared-workspace
