apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app.kubernetes.io/component: github-webhook-service
    app.kubernetes.io/name: github-webhook-service
    app.kubernetes.io/part-of: okd-operator-pipeline
    app.kubernetes.io/version: v0.0.1
  name: github-webhook-service
  namespace: okd-team
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: github-webhook-service
      app.kubernetes.io/name: github-webhook-service
      app.kubernetes.io/part-of: okd-operator-pipeline
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: github-webhook-service
        app.kubernetes.io/name: github-webhook-service
        app.kubernetes.io/part-of: okd-operator-pipeline
        app.kubernetes.io/version: v0.0.1
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: info
        - name: PR_OPENED_URL
          value: ""
        - name: PR_MERGED_URL
          value: "http://okd-trigger-example-el:8080"
        - name: PRERELEASED_URL
          value: ""
        - name: RELEASED_URL
          value: ""
        image: quay.io/luzuccar/golang-gitwebhook-service:v0.0.1
        imagePullPolicy: Always
        name: github-webhook-service
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/isalive
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 200Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      
