apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: github-webhook-service
    app.kubernetes.io/name: github-webhook-service
    app.kubernetes.io/part-of: okd-operator-pipeline
    app.kubernetes.io/version: v0.0.1
  name: github-webhook-service
  namespace: okd-team
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/component: github-webhook-service
    app.kubernetes.io/name: github-webhook-service
    app.kubernetes.io/part-of: okd-operator-pipeline
  sessionAffinity: None
  type: ClusterIP
