apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../../manifests/tekton/tasks/base
  - ../../../manifests/tekton/pipelines/base
  - ../../../manifests/tekton/triggers/base
namespace: okd-team

patchesJson6902:
- path: patches/patch-envars.yaml
  target:
    group: tekton.dev
    kind: Task
    name: okd-trigger-example-test
    version: v1beta1


